if has('nvim')
  set listchars+=eol:$
  set runtimepath^=~/.vim
  set runtimepath+=~/.vim/after
  set runtimepath+=~/.vim/plugin
  let &packpath = &runtimepath
else
  set autoindent
  set backspace=indent,eol,start
  set hidden
  set hlsearch incsearch
  set pastetoggle=<C-s>
  set showcmd
  set laststatus=2
  set ttymouse=sgr
  filetype plugin indent on
endif

set backupdir^=$HOME/.vim/tmp// directory^=$HOME/.vim/tmp//
set ignorecase smartcase
set mouse=a
set nowrap
set scrolloff=1
set showbreak=>\ 
set smartindent
set statusline=%F\ %r%m%=L%l/%L\ %y
let g:netrw_banner = 0

inoremap <C-a> <esc>0i
inoremap <C-e> <esc>$i<right>
nnoremap <Backspace> <C-b>
nnoremap <Space> <C-f>
nnoremap <C-n> :bnext<cr>
nnoremap <C-p> :bprevious<cr>
nnoremap <cr> :nohlsearch<cr>
nnoremap <leader>d :read !datehead<cr>
nnoremap <leader>l :lcd %:p:h<cr>
nnoremap <leader>r :read !<C-r><C-l><cr>
nnoremap <leader>t :belowright terminal<cr>i
nnoremap <leader>u yypVr-
nnoremap <leader><Backspace> :%s/\s\+$//e<cr>:nohlsearch<cr>:echo "Removed trailing whitespace."<cr>
nnoremap <Tab> za
vnoremap ; "+y

augroup whitespace
  autocmd!
  autocmd InsertEnter * match TrailingWhitespace /\s\+\%#\@<!$/
  autocmd BufWritePost,InsertLeave * match TrailingWhitespace /\s\+$/
  autocmd ColorScheme * hi link TrailingWhitespace SpellBad
augroup END

" enable italics
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

colorscheme calm

if !exists('g:vscode')
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | runtime $MYVIMRC
  endif
  call plug#begin('~/.vim/plug')
  Plug 'LnL7/vim-nix'
  Plug 'mhinz/vim-signify'
  Plug 'chrisbra/Colorizer'
  Plug 'hrsh7th/nvim-cmp'
  Plug 'neovim/nvim-lspconfig'
  Plug 'tpope/vim-commentary'
  call plug#end()

