if !has('nvim')
  set fillchars=vert:\│
  set pastetoggle=<C-s>
  set ttymouse=sgr
  let s:datadir = !empty($XDG_DATA_HOME) ? $XDG_DATA_HOME : $HOME.'/.local/share/vim'
  let s:statedir = !empty($XDG_STATE_HOME) ? $XDG_STATE_HOME : $HOME.'/.local/state/vim'
  call mkdir(s:datadir, 'p', 0700)
  call mkdir(s:statedir .'/backup', 'p', 0700)
  call mkdir(s:statedir .'/swap', 'p', 0700)
  let &viminfofile = s:statedir . '/viminfo'
  let &backupdir = s:statedir . '/backup//,' . &backupdir
  let &directory = s:statedir . '/swap//,' . &directory
  let g:netrw_home = s:datadir
endif

filetype plugin indent on
set autoindent copyindent smartindent
set ignorecase smartcase
set hidden
set hlsearch incsearch
set laststatus=2
set mouse=a
set showbreak=>\
set splitbelow splitright
set tabstop=4 shiftwidth=0
set textwidth=80

set statusline=
set statusline+=%{GitPath()}
set statusline+=\ %{get(b:,'git_branch','')}
set statusline+=%(\ %r%m%q%)
set statusline+=%=
set statusline+=%l/%L
set statusline+=\ %y

inoremap <buffer> () ()<esc>i
inoremap <C-a> <esc>0i
inoremap <C-e> <esc>$i<right>
nnoremap <Backspace> <C-b>
nnoremap <Space> <C-f>
nnoremap <C-n> :bnext<cr>
nnoremap <C-p> :bprevious<cr>
nnoremap <cr> :nohlsearch<cr>
nnoremap <leader>d :read !datehead<cr>
nnoremap <leader>l :lcd %:p:h<cr>
nnoremap <leader>r :read !<C-r><C-l><cr>
nnoremap <leader>t :belowright terminal<cr>i
nnoremap <leader>u yypVr-
vnoremap <leader>y "+y
nnoremap <leader><Backspace> :%s/\s\+$//e<cr>:nohlsearch<cr>:echo "Removed trailing whitespace."<cr>
nnoremap <Tab> za

augroup whitespace
  autocmd!
  autocmd InsertEnter * match TrailingWhitespace /\s\+\%#\@<!$/
  autocmd BufWritePost,InsertLeave * match TrailingWhitespace /\s\+$/
  autocmd ColorScheme * hi link TrailingWhitespace SpellBad
augroup END

augroup colorOverrides
  autocmd ColorScheme * hi! link hoonArm Identifier
  autocmd ColorScheme * hi! link hoonAtomType Type
  autocmd ColorScheme * hi! link hoonCubeType Type
  autocmd ColorScheme * hi! link hoonNumber Number
  autocmd ColorScheme * hi! link scalaCapitalWord Type
  autocmd ColorScheme * hi! link scalaInstanceDeclaration Identifier
  autocmd ColorScheme * hi! link scalaSpecial Normal
augroup END

let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
let g:netrw_banner = 0

colorscheme calm

if !has('nvim')
  if empty(glob('~/.config/vim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | runtime $MYVIMRC
  endif
  call plug#begin('~/.config/vim/plug')
  Plug 'mhinz/vim-signify'
  Plug 'chrisbra/Colorizer'
  call plug#end()
endif
