set -g  default-terminal   tmux-256color
set -g  focus-events       on
set -g  history-limit      10000
set -g  mouse              on
set -g  pane-scrollbars    off
set -g  renumber-windows   on
set -g  set-titles         on
set -ga terminal-features  ",xterm-*:RGB,ccolour,clipboard,cstyle,focus,hyperlinks,margins,mouse,osc7,overline,rectfill,sixel,strikethrough,sync,title,usstyle"

bind-key    \\ split-window -h -c "#{pane_current_path}"
bind-key    -  split-window    -c "#{pane_current_path}"
bind-key    h select-pane -L
bind-key    l select-pane -R
bind-key    j select-pane -D
bind-key    k select-pane -U
bind-key -n M-\{ previous-window
bind-key -n M-\} next-window

set -g copy-mode-match-style          fg=terminal,underscore,bg=colour7
set -g copy-mode-current-match-style  reverse
set -g menu-selected-style            fg=terminal,bg=colour7
set -g message-style                  fg=terminal,bg=colour7
set -g mode-style                     fg=terminal,bg=colour7
set -g pane-active-border-style       fg=terminal
set -g pane-border-style              fg=terminal
set -g pane-border-format             '\ #{pane_title}'
set -g pane-scrollbars-style          fg=colour7
set -g status-style                   fg=terminal
set -g window-status-current-style    fg=terminal


if-shell '[ "$TERMUX_VERSION" ]' \
	" \
	set -g menu-selected-style fg=terminal,underscore; \
	set -g message-style fg=terminal,underscore; \
	set -g mode-style fg=terminal,bg=terminal,underscore; \
	set -g pane-border-status off; \
	set -g pane-border-indicators off; \
	set -g status 2; \
	set -g status-format[1] '#[fg=terminal]#{pane_title}'; \
	set -g status-right '' \
	"
if-shell '[ "$EINK" ]' \
	" \
	set -g mode-style fg=terminal,underscore; \
	set -g status-interval 0 \
	"

